name: Publish

on:
  push:
    tags:
      - "loopwatch@*"
      - "loopwatch-playwright@*"
      - "loopwatch-react@*"

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v6
      - uses: oven-sh/setup-bun@v2
      - run: bun install --frozen-lockfile

      - name: Check loopwatch
        if: startsWith(github.ref_name, 'loopwatch@')
        run: bun run lint && bun run type-check && bun run test
        working-directory: packages/core

      - name: Publish loopwatch
        if: startsWith(github.ref_name, 'loopwatch@')
        run: bunx jsr publish
        working-directory: packages/core

      - name: Check loopwatch-playwright
        if: startsWith(github.ref_name, 'loopwatch-playwright@')
        run: bun run lint && bun run type-check
        working-directory: packages/playwright

      - name: Build loopwatch-playwright
        if: startsWith(github.ref_name, 'loopwatch-playwright@')
        run: bun run build
        working-directory: packages/playwright

      - name: Publish loopwatch-playwright
        if: startsWith(github.ref_name, 'loopwatch-playwright@')
        run: bunx jsr publish
        working-directory: packages/playwright

      - name: Check loopwatch-react
        if: startsWith(github.ref_name, 'loopwatch-react@')
        run: bun run lint && bun run type-check && bun run test
        working-directory: packages/react

      - name: Publish loopwatch-react
        if: startsWith(github.ref_name, 'loopwatch-react@')
        run: bunx jsr publish
        working-directory: packages/react
